pre-release-replacements = [
    {file="src/lib.rs", search="html_root_url = \"https://docs.rs/doctor/[a-z0-9\\.-]+\"", replace="html_root_url = \"https://docs.rs/doctor/{{version}}\""},
]
pre-release-hook = ["make", "pre-release"]